### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by mak0275** [nao20010128nao/private-key-recovery-tool#2]
npm ERR! code 1
npm ERR! git dep preparation failed
npm ERR! command /usr/local/bin/node /usr/local/lib/node_modules/npm/bin/npm-cli.js install --force --cache=/home/mak0275/.npm --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit
npm ERR! > tiny-secp256k1@1.0.0 install
npm ERR! > node-gyp rebuild
npm ERR!
npm ERR! make: Entering directory '/home/mak0275/.npm/_cacache/tmp/git-clone-1d1dbce1/build'
npm ERR!   CXX(target) Release/obj.target/secp256k1/native/addon.o
npm ERR! secp256k1.target.mk:153: recipe for target 'Release/obj.target/secp256k1/native/addon.o' failed
npm ERR! make: Leaving directory '/home/mak0275/.npm/_cacache/tmp/git-clone-1d1dbce1/build'
npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@15.11.0 | linux | x64
npm ERR! gyp info find Python using Python version 3.6.9 found at "/usr/bin/python3"
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/mak0275/.npm/_cacache/tmp/git-clone-1d1dbce1/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/mak0275/.cache/node-gyp/15.11.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/mak0275/.cache/node-gyp/15.11.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/mak0275/.cache/node-gyp/15.11.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/home/mak0275/.npm/_cacache/tmp/git-clone-1d1dbce1',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! ../native/addon.cpp:5:10: fatal error: secp256k1.h: No such file or directory
npm ERR!  #include <secp256k1.h>
npm ERR!           ^~~~~~~~~~~~~
npm ERR! compilation terminated.
npm ERR! make: *** [Release/obj.target/secp256k1/native/addon.o] Error 1
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:378:20)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! gyp ERR! System Linux 4.4.0-17763-Microsoft
npm ERR! gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /home/mak0275/.npm/_cacache/tmp/git-clone-1d1dbce1
npm ERR! gyp ERR! node -v v15.11.0
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok
npm ERR! npm ERR! code 1
npm ERR! npm ERR! path /home/mak0275/.npm/_cacache/tmp/git-clone-1d1dbce1
npm ERR! npm ERR! command failed
npm ERR! npm ERR! command sh -c node-gyp rebuild
npm ERR!
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR!     /home/mak0275/.npm/_logs/2021-03-09T14_42_38_620Z-debug.log

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mak0275/.npm/_logs/2021-03-09T14_42_55_717Z-debug.log

can u help me please

**Comment by Lesmiscore** [comment]
Please report this error at `tiny-secp256k1`, instead of here.

**Comment by nao20010128nao** [comment]
Please report this error at `tiny-secp256k1`, instead of here.
